const Antonym = [
  { word: "abhor", antonym: "admire,approve,covet,crave,desire,enjoy,esteem,esteem,like,love,relish" },
  { word: "abide", antonym: "abandon,avoid,depart,forfeit,forfend,journey,migrate,move,proceed,reject,resist,shun" },
  { word: "abscond", antonym: "show,emerge,appear" },
  { word: "acclaim", antonym: "abuse,animadversion,blame,censure,condemnation,contempt,denunciation,disapprobation,disapproval,disparagement,hissing,ignominy,obloquy,reproach,reproof,repudiation,scorn,slander,vilification,vituperation" },
  { word: "accolade", antonym: "" },
  { word: "acumen", antonym: "bluntness,dulness,obtuseness,stupidity" },
  { word: "admonish", antonym: "abet,applaud,approve,cheer,countenance,encourage,impel,incite,instigate,urge on" },
  { word: "adorn", antonym: "deface,deform,disfigure,mar,spoil" },
  { word: "adulteration", antonym: "purification" },
  { word: "adumbrate", antonym: "" },
  { word: "affable", antonym: "unfriendly" },
  { word: "aggravate", antonym: "conciliate,content,gratify,honor,please" },
  { word: "allegiance", antonym: "disaffection,disloyalty,rebellion,sedition,treason" },
  { word: "alleviate", antonym: "aggravate,augment,embitter,enhance,heighten,increase,intensify,magnify,make worse" },
  { word: "amalgamate", antonym: "divided" },
  { word: "ambiguous", antonym: "unambiguous" },
  { word: "ameliorate", antonym: "aggravate,blemish,corrupt,debase,depress,deteriorate,harm,impair,injure,mar,spoil,tarnish,vitiate" },
  { word: "anguish", antonym: "aggravate,augment,embitter,enhance,heighten,increase,intensify,magnify,make  satisfaction,tranquillity" },
  { word: "antidote", antonym: "" },
  { word: "appease", antonym: "antagonize" },
  { word: "arrogance", antonym: "bashfulness,servility,considerateness,deference,courtesy,modesty,shyness,diffidence,politeness" },
  { word: "ascend", antonym: "descend" },
  { word: "audacious", antonym: "shy,cautious,prudent" },
  { word: "braggart", antonym: "humble" },
  { word: "brittle", antonym: "tempered,warmhearted,unbreakable,treated,hardened,toughened" },
  { word: "catalyst", antonym: "anticatalyst" },
  { word: "chisel", antonym: "" },
  { word: "clientele", antonym: "" },
  { word: "combustion", antonym: "" },
  { word: "commemorate", antonym: "contemn,despise,dishonor,disregard,forget,ignore,neglect,overlook,profane,violate" },
  { word: "complaisant", antonym: "unobliging,unaccommodating" },
  { word: "conceal", antonym: "reveal,admit,uncover" },
  { word: "conjoin", antonym: "abstract,appropriate,detach,discriminate,distinguish,distract,divert,eliminate,purloin,remove,separate,steal,take away,withdraw" },
  { word: "connote", antonym: "" },
  { word: "cryptic", antonym: "exoteric,explicable,prolix" },
  { word: "dangle", antonym: "" },
  { word: "defer", antonym: "abbreviate,abridge,conclude,contract,curtail,hasten,hurry,limit,reduce,shorten" },
  { word: "disallow", antonym: "countenance,let,permit,allow" },
  { word: "divergence", antonym: "convergence" },
  { word: "dormant", antonym: "active" },
  { word: "dote", antonym: "" },
  { word: "dullard", antonym: "" },
  { word: "dwarf", antonym: "ettin,giant" },
  { word: "edible", antonym: "inedible" },
  { word: "eloquence", antonym: "" },
  { word: "embezzle", antonym: "square,balance,clear" },
  { word: "encapsulate", antonym: "" },
  { word: "endeavor", antonym: "abandon,dismiss,drop,give up,let go,neglect,omit,overlook,pass by,throw away,throw over,throw up" },
  { word: "engulf", antonym: "" },
  { word: "entice", antonym: "chill,damp,deter,dissuade,drive away,repel,warn" },
  { word: "eradicate", antonym: "authorize,cherish,confirm,continue,enact,establish,institute,introduce,legalize,promote,reinstate,renew,repair,restore,revive,set up,support,sustain" },
  { word: "evoke", antonym: "allay,stifle,stop,silence,prevent,seal" },
  { word: "extinct", antonym: "extant,active" },
  { word: "extinguish", antonym: "ignite" },
  { word: "fission", antonym: "" },
  { word: "fragrant", antonym: "malodorous" },
  { word: "gait", antonym: "" },
  { word: "gallant", antonym: "spiritless,discourteous,cowardly,unimpressive,fearful,discourteous" },
  { word: "gerontocracy", antonym: "" },
  { word: "grievous", antonym: "unimportant,joyful,noncritical,good,noncrucial" },
  { word: "grumble", antonym: "applaud,approve,commend,eulogize,laud,praise" },
  { word: "heterogeneous", antonym: "homogeneous" },
  { word: "hypocrisy", antonym: "candor,frankness,genuineness,honesty,ingenuousness,openness,sincerity,transparency,truth,truthfulness" },
  { word: "impermeable", antonym: "permeable" },
  { word: "indigenous", antonym: "acquired,alien,alien,artificial,assumed,foreign,unnatural" },
  { word: "infuriate", antonym: "" },
  { word: "ingest", antonym: "" },
  { word: "inquest", antonym: "" },
  { word: "introspect", antonym: "" },
  { word: "invincible", antonym: "conquerable,weak,spiritless,powerless,puny,effortless" },
  { word: "judicious", antonym: "imprudent,absurd,dull,foolish,futile,ignorant,irrational,obtuse,senseless,silly,simple,sottish,stupid,undiscerning,unintelligent" },
  { word: "livid", antonym: "unangry,uninjured,dark,colourful,colorful" },
  { word: "loll", antonym: "rise,stir" },
  { word: "malevolent", antonym: "unmalicious,beneficent" },
  { word: "massacre", antonym: "" },
  { word: "moribund", antonym: "nascent,dynamic,dynamical" },
  { word: "narcissism", antonym: "" },
  { word: "nihilism", antonym: "" },
  { word: "odor", antonym: "inodorousness,absence of smell,want of smell" },
  { word: "offhand", antonym: "prepared,careful" },
  { word: "opaque", antonym: "clear" },
  { word: "ossified", antonym: "flexible" },
  { word: "poseur", antonym: "" },
  { word: "premature", antonym: "full-term,mature" },
  { word: "reconcile", antonym: "separate,sever,dissever,estrange,disharmonize,derange,alienate" },
  { word: "reiterate", antonym: "cancel,withdraw,reverse,retract" },
  { word: "rejuvenation", antonym: "" },
  { word: "relapse", antonym: "advance,advancement,attainment,development,growth,improvement,increase,proficiency,progress,progression,recover,amend" },
  { word: "reminiscent", antonym: "mindless,unmindful,forgetful" },
  { word: "renovate", antonym: "" },
  { word: "renown", antonym: "contempt,contumely,discredit,disgrace,dishonor,disrepute,humiliation,ignominy,infamy,oblivion,obscurity,shame" },
  { word: "riddle", antonym: "answer,axiom,explanation,proposition,solution" },
  { word: "sadistic", antonym: "masochistic" },
  { word: "salvage", antonym: "" },
  { word: "sanction", antonym: "baffle,confound,counteract,denounce,deter,disapprove,disconcert,discourage,dissuade,expose,frustrate,hinder,impede,obstruct" },
  { word: "sanity", antonym: "aberration,alienation,craziness,delirium,dementia,derangement,frenzy,hallucination,insanity,lunacy,madness,mania,monomania" },
  { word: "scribble", antonym: "" },
  { word: "shallow", antonym: "deep,sound,unfathomable,unsounded,unfathomed,heavy,profound,abysmal,bottomless,abyssal,unplumbed,wakeless" },
  { word: "shard", antonym: "" },
  { word: "shun", antonym: "admire,approve,covet,crave,desire,enjoy,esteem,esteem,like,love,relish" },
  { word: "sluggard", antonym: "" },
  { word: "sporadic", antonym: "continual,unrelenting,repetitive,recurring,perennial,revenant,relentless,running(a), recurrent,insistent,persistent,repeated" },
  { word: "submerge", antonym: "raise,extricate,educe" },
  { word: "succumb", antonym: "survive,come through,pull through,pull round,make it" },
  { word: "surcharge", antonym: "" },
  { word: "tadpole", antonym: "" },
  { word: "timid", antonym: "brave,bold" },
  { word: "turmoil", antonym: "order,regularity" },
  { word: "vigorous", antonym: "unenrgetic,lethargic,frail" },
  { word: "yarn", antonym: "" },
];

export default Antonym;